### ISSUE TITLE
can I mask in price format ?

### ISSUE THREAD

**Issue by murilolivorato** [moip/awesome-mask#16]
Hello my frind , nice code !  congratulation .
can I mask in price format ? like this 

I type this -
```
7000020
```

and do it -

```
70.000,20
```

**Comment by iCaio** [comment]
Hi @murilolivorato , we do not support money format since its a reversive typing.

I have tested: 
http://www.giphy.com/gifs/l1KVatI3cl4vZlbNK

This is a good feature, I will add this to our backlog, okay?

**Comment by iCaio** [comment]
@murilolivorato I will make a release this week with money mask support.

**Comment by iCaio** [comment]
https://moip.github.io/awesome-examples/

Money support added on 0.5.0 

https://github.com/moip/awesome-mask/releases/tag/0.5.0

**Comment by marcusvbp** [comment]
Hi @iCaio, this feature is not working. I can't type any value, the field only show "money" as value.

<input type="text" class="form-control" id="valorproducao" v-model="formData.price" v-mask="'money'">

Here is my package.json:

"dependencies": {
    "awesome-mask": "^0.5.0",
    "jquery": "^3.2.1",
    "vue": "^2.2.1",
    "vue-gmaps": "^0.2.1",
    "vue-multiselect": "^2.0.0-beta.15",
    "vue-router": "^2.3.0",
    "vue-style-loader": "^2.0.4",
    "vuejs-datepicker": "^0.6.5",
    "vuelidate": "^0.4.2",
    "vuex": "^2.2.1"
  },

**Comment by iCaio** [comment]
https://github.com/moip/awesome-examples

Can you please try this project? Can you reproduce the problem with a gist? @marcusvbp

**Comment by iCaio** [comment]
I am fixing it @marcusvbp

**Comment by iCaio** [comment]
Can you please test the version 0.5.1?

**Comment by marcusvbp** [comment]
@iCaio I will! thanks.

**Comment by marcusvbp** [comment]
It worked, but I have noticied the variable bind has a different value from the field. Look at the screenshot:

![Uploading screenshot-localhost-8080-2017-04-10-18-00-05.png…]()

**Comment by iCaio** [comment]
Hi @marcusvbp , can you try version 0.5.2?

**Comment by marcusvbp** [comment]
I have tried but no success:
![screenshot-localhost-8080-2017-04-11-10-32-38](https://cloud.githubusercontent.com/assets/4376611/24911754/72e6ea30-1ea2-11e7-8b51-0659970a6889.png)
![screenshot-localhost-8080-2017-04-11-10-28-19](https://cloud.githubusercontent.com/assets/4376611/24911755/72e83d68-1ea2-11e7-8fcd-dc77d172f350.png)

**Comment by marcusvbp** [comment]
@iCaio it worked in my project, after server restart.

Thanks!
