### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by rvizcaino80** [moip/awesome-mask#18]
Sorry, this is not an issue. I can not figure it out how to use it. This is my code: 

import AwesomeMask from "awesome-mask";
new Vue({
        el: "#my-vue-element",
        directives: {
            "mask": AwesomeMask
        }
});

I get this: [Vue warn]: Property or method "mask" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option. 
(found in <Root>)

Thanks for your help.

**Comment by gabemule** [comment]
You should use it in your desired component, and use the directive in the template..

**Comment by iCaio** [comment]
https://github.com/moip/awesome-examples/blob/master/src/App.vue

You can check an example here @rvizcaino80
