### ISSUE TITLE
Money mask Placeholder

### ISSUE THREAD

**Issue by gabemule** [moip/awesome-mask#19]
I am using v-mask="'money'" for currency/money and it works correctly, but the input text shows 'money' instead of the desired placeholder, how can i avoid this default 'money' placeholder to show?

**Comment by iCaio** [comment]
Can you give me a fiddle with the problem? The placeholder is working fine here:
```
<input v-mask="'money'" placeholder="PLACEHOLDER" class="mdl-textfield__input" type="text" id="sample4">
```

<img width="514" alt="screen shot 2017-04-13 at 14 51 43" src="https://cloud.githubusercontent.com/assets/1437058/25017056/be0ab246-2058-11e7-934f-6ebf6e7069b5.png">
