### ISSUE TITLE
Not downloading on npm

### ISSUE THREAD

**Issue by BRKsDeadPool** [moip/awesome-mask#2]
## Hello, 
i was trying to download the package with "npm i --save awesome-mask" but the download crash after a few seconds.

May be this is a npm issue ?

**Comment by iCaio** [comment]
Hi @BRKsDeadPool we have tested on five devices this week (using effectively the mask) and we are not having problems with installation.

Can you run `npm i --save awesome-mask@0.3.0` ?

**Comment by BRKsDeadPool** [comment]
Same thing.

![capturar](https://cloud.githubusercontent.com/assets/16820868/22834373/0a498d6e-ef9c-11e6-847f-81e2f67adfe7.PNG)

**Comment by iCaio** [comment]
I think this is a problem in the npm repository, Can you test in another computer?

**Comment by alexsandro-xpt** [comment]
Same to me...

**Comment by iCaio** [comment]
@alexsandro-xpt using Windows?

**Comment by iCaio** [comment]
Also, can you see your node and npm version?

**Comment by alexsandro-xpt** [comment]
Yes, using Windows @iCaio Node Version: v7.5.0, NPM Version: 4.1.2

**Comment by iCaio** [comment]
@alexsandro-xpt I have removed the Vue dependency on `0.3.1`, can you try these? On the print, the problem is on installing the dependency of the awesome-mask.

**Comment by alexsandro-xpt** [comment]
Same thing, not work...

**Comment by iCaio** [comment]
I am sorry @alexsandro-xpt but I need to find a computer with Windows to investigate this problem, this can take some time.

**Comment by iCaio** [comment]
Changed the depedency at 0.3.3 version(only and specific this), please try these one.

**Comment by alexsandro-xpt** [comment]
Thank you so much @iCaio, package instalation is done with awesome-mask@0.3.3

**Comment by iCaio** [comment]
@alexsandro-xpt @BRKsDeadPool Vanilla Masker now supports Windows, you can update the Awesome-Mask to latest version 😄
