### ISSUE TITLE
Opção para remover o valor se não completar a mascara.

### ISSUE THREAD

**Issue by Tagliatti** [moip/awesome-mask#20]
Olá, atualmente tem essa opção? Não consegui encontrar.
EX: Mask with Clear If Not Match Option do https://igorescobar.github.io/jQuery-Mask-Plugin/

**Comment by icaioincau** [comment]
Não temos, não pretendemos colocar essa função tão cedo @Tagliatti, nós fazemos isso no nosso módulo de validação(que ainda não é open source).
