### ISSUE TITLE
Utilização de máscara alfa numérico (texto e número)

### ISSUE THREAD

**Issue by evertramos** [moip/awesome-mask#21]
Olá Pessoa,

Excelente trabalho! Obrigado!

Estou tentando utilizar uma máscara que limita a 5 caracteres, podendo ser alfa numéricos, exemplo:

```
V25BM
23BTH
Y5H77
```
*Sem um padrão como no caso de uma placa de carro *AAA-9999*.

Já existe essa possibilidade ou como poderia implementar essa opção?

Grato!

**Comment by icaioincau** [comment]
SSSSS deve resolver.

**Comment by evertramos** [comment]
Legal!!!

Vou colocar na documentação depois.

Valeu!
