### ISSUE TITLE
Usage with Component input

### ISSUE THREAD

**Issue by matheusgrieger** [moip/awesome-mask#25]
Is it possible to use together with component inputs, such as [Vuetify's Text fields](https://vuetifyjs.com/components/text-fields)?

I've tried and it throws a "Cannot read property 'length' of undefined" error.

**Comment by icaioincau** [comment]
No, it only works with native html input.

**Comment by matheusgrieger** [comment]
As I really, really needed this, I've opened a Pull Request #26 adding support for Components such as Vuetify's Text fields.

I have tested with them, and also ran the tests from test folder, and all passed. I'll thank you a lot if you were to approve it, since we are in need to use your directive.

**Comment by icaioincau** [comment]
PR merged @matheusgrieger , thanks.
