### ISSUE TITLE
Event is not a constructor' error everytime I type in v-mask

### ISSUE THREAD

**Issue by koroda** [moip/awesome-mask#28]
On every place I use v-mask, every change that i have on the text throws an 'Event is not a constructor' error.

It works normally and the way expected, but keeps throwing this error. Anyone knows what could be?

**Comment by whyleee** [comment]
You can add `Event` polyfill for IE, see [related SO question answers](https://stackoverflow.com/questions/26596123/internet-explorer-9-10-11-event-constructor-doesnt-work). This will fix the errors.

**Comment by inodaf** [comment]
@koroda This issue was resolved at #29.

**Comment by icaioincau** [comment]
Fixed on 1.0.10
