### ISSUE TITLE
Valores negativos

### ISSUE THREAD

**Issue by rodrigo-campero** [moip/awesome-mask#32]
I'm using the framework quasar and I have a problem when the value is negative, the v-mask directive does not accept, how can I find a solution?
![value nagative](https://user-images.githubusercontent.com/23708939/34487721-f5a7b29e-efab-11e7-8131-049546faad93.png)

**Comment by icaioincau** [comment]
Hi @rodrigo-campero, for now, we don't support to negative money and since we are not using negative money values here, we are not planning to implement soon.

We will be grateful if you open a PR with this feature.

**Comment by icaioincau** [comment]
The main problem is that Vanilla Masker doesn't support it: https://github.com/vanilla-masker/vanilla-masker/issues/97

**Comment by icaioincau** [comment]
Try version 1.1.1 released today,added support.

**Comment by icaioincau** [comment]
Working here: https://moip.github.io/awesome-examples/

**Comment by rodrigo-campero** [comment]
Thank you
