### ISSUE TITLE
How do i import awesome-mask on my project? 

### ISSUE THREAD

**Issue by firminoweb** [moip/awesome-mask#5]
The README file has only example ways to use it, but, has no the basic information about import that.

```
import * from 'awesome-mask' ?
``` 

```
import awesomeMask from 'awesome-mask'
//
Vue.use(awesomeMask) ??
``` 

Thanks!

**Comment by guigmaster** [comment]
import Hello from './components/Hello'
import AwesomeMask from 'awesome-mask'
export default {
  name: 'app',
  components: {
    Hello
  },
  directives: {
    'mask': AwesomeMask
  }
}

**Comment by firminoweb** [comment]
@guigmaster Works! thank you!!

**Comment by iCaio** [comment]
Closed :) Thanks @deividmarques
