### ISSUE TITLE
Apply mask to default value.

### ISSUE THREAD

**Issue by xereda** [moip/awesome-mask#7]
First of all, congratulations for the initiative. Excellent job.

How do I get the value to be formatted in an assignment to the v-model variable?

The mask works in the course of typing only. Is there a way to apply the mask to the default value of an input?

Thank you very much for your time.

**Comment by iCaio** [comment]
Hi @xereda, thanks! You can't just format your default value with a getter or a computed property?

**Comment by xereda** [comment]
Excuse me, but I do not understand. The mask is only applied when the field is typed, right? How do I make the value formatted without typing? What I need is to set the mask, set in the "v-mask" property, when I assign a value to the variable of my v-model. When you open the form with the value filled in, the mask has already been applied to the field.

**Comment by iCaio** [comment]
We do not have this feature yet, I wil discuss with moip team about the viability of this feature.

**Comment by iCaio** [comment]
Support added to default value at version `0.3.6`

**Comment by xereda** [comment]
Yeah! It's working perfectly! Many thanks, my friend.
