### ISSUE TITLE
Unsupported characters kept on the value after blur

### ISSUE THREAD

**Issue by guilhermewaess** [moip/awesome-mask#8]
Hi fellows!

First of all, nice work, is always good to have people in a private companies opening usefull codes for a community

I'm looking for a input mask to use on my project, and testing your demo, I found a strange behavior, for example:

On car plate, first 3 characters must be a letter, if I type a number, and get out the focus of the component, the number stayed on field... I'm not sure if the number still on value var, but is weird to see a number instead a letter.

![image](https://cloud.githubusercontent.com/assets/5339165/23477877/349e30e0-fe9e-11e6-85ba-e6a70b97ff4e.png)

Maybe this problem is on keyDown event: el.addEventListener('keydown', inputHandler), maybe is better keyUp event. But is just a shot, I really dont know the code ;)

Well is it.

**Comment by iCaio** [comment]
Thanks @guilhermewaess , the tab was working, I can reproduce the problem with direct click on another field.

Already pathed: https://github.com/moip/awesome-mask/pull/9
